### ISSUE TITLE
I'm getting an error!!

### ISSUE THREAD

**Issue by JainSahit** [ranjeet867/google-play-crawler#1]
Traceback (most recent call last):
  File "appCrawler.py", line 32, in <module>
    print("App name: ", expatistan_table.string)
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by AlanSyue** [comment]
> Traceback (most recent call last):
> File "appCrawler.py", line 32, in 
> print("App name: ", expatistan_table.string)
> AttributeError: 'NoneType' object has no attribute 'string'

Hi JainSahit , because Google changed the tag from div to h1 , and the class name from id-app-title to AHFaub , you can try " expatistan_table = soup_expatistan.find("h1", class_="AHFaub")" , I think it can solve your problem.
